version: "3.7"

networks:
  hillel-network:
    name: hillel-network
#    external: true
  hillel-proxy.network:
    name: hillel-proxy.network
#    external: true

services:
  hillel-app:
    container_name: hillel-app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on:
      - hillel-mysql
      - hillel-redis
    volumes:
      - ./:/app:cached
    extra_hosts:
      - "host.docker.internal:host-gateway" #for xDebug
    networks:
      - hillel-network

  hillel-app-nginx:
    container_name: hillel-app-nginx
    build:
      context: ./docker/nginx
    depends_on:
      - hillel-app
    volumes:
      - ./public:/app/public:cached
    networks:
      - hillel-network
      - hillel-proxy.network
    labels:
      - traefik.enable=true
      - traefik.http.routers.hillel-nginx.rule=Host(`hillel.localhost`)

  hillel-redis:
    container_name: hillel-redis
    build:
      context: ./docker/redis
    command: redis-server --appendonly yes
    hostname: "redis"
    volumes:
      - hillel-redis-storage:/data
    networks:
      - hillel-network
      - hillel-proxy.network
    labels:
      - traefik.enable=true
      - traefik.tcp.services.hillel-redis.loadBalancer.server.port=6379
      - traefik.tcp.routers.hillel-redis.entrypoints=redis
      - traefik.tcp.routers.hillel-redis.rule=HostSNI(`*`)
      - traefik.tcp.routers.hillel-redis.service=hillel-redis

  hillel-mysql:
    container_name: hillel-mysql
    build:
      context: ./docker/mysql
    volumes:
      - hillel-mysql-storage:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - hillel-network
      - hillel-proxy.network
    labels:
      - traefik.enable=true
      - traefik.tcp.services.hillel-mysql.loadBalancer.server.port=3306
      - traefik.tcp.routers.hillel-mysql.entrypoints=mysql
      - traefik.tcp.routers.hillel-mysql.rule=HostSNI(`*`)
      - traefik.tcp.routers.hillel-mysql.service=hillel-mysql

  hillel-rabbit:
    container_name: hillel-rabbit
    build:
      context: ./docker/rmq
    volumes:
      - hillel-rabbit-storage:/var/lib/rabbitmq
    networks:
      - hillel-network
      - hillel-proxy.network
    labels:
      - traefik.enable=true
      - traefik.tcp.services.hillel-rabbit.loadBalancer.server.port=5672
      - traefik.tcp.routers.hillel-rabbit.entrypoints=rabbit
      - traefik.tcp.routers.hillel-rabbit.rule=HostSNI(`*`)
      - traefik.tcp.routers.hillel-rabbit.service=hillel-rabbit

  hillel-proxy:
    container_name: hillel-proxy
    image: traefik:v2.5
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=hillel-proxy.network
      - --providers.docker.useBindPortIP=false
      - --entrypoints.web.address=:80
      - --entrypoints.redis.address=:6379
      - --entrypoints.mysql.address=:3306
      - --entrypoints.rabbit.address=:5672
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "6379:6379"
      - "3306:3306"
      - "5672:5672"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hillel-proxy.network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`hillel-proxy.localhost`)"
      - "traefik.http.routers.api.service=api@internal"

volumes:
  hillel-redis-storage:
  hillel-mysql-storage:
  hillel-rabbit-storage:
